./augment.pl wmt102.test08/csNa+form
./augment.pl wmt102.test09/csNa+form
./augment.pl czeng092-ne/csNa+form
./augment.pl czeng092-su/csNa+form
./augment.pl czeng092-te/csNa+form
./augment.pl czeng092-we/csNa+form
./augment.pl czeng092-eu/csNa+form
./augment.pl czeng092-fi/csNa+form
./augment.pl czeng092-na/csNa+form
./augment.pl emea2/csNa+form
./augment.pl wmt10mono2/csNa+form

./augment.pl wmt102.test08/enNa+form
./augment.pl wmt102.test09/enNa+form
./augment.pl czeng092-ne/enNa+form
./augment.pl czeng092-su/enNa+form
./augment.pl czeng092-te/enNa+form
./augment.pl czeng092-we/enNa+form
./augment.pl czeng092-eu/enNa+form
./augment.pl czeng092-fi/enNa+form
./augment.pl czeng092-na/enNa+form
./augment.pl emea2/enNa+form
