#!/bin/bash
# eman step to support makecorpus.pl
# Three modes of operation:
#   RUN_COMMAND=...
#   RESTRICT_TO_FACTOR=...
#   COMBINE_PARTS=...

XXX

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# Ensure all the required variables are set (or provide the default)
eman defvar CZENG_SOURCEDIR default='/net/data/czeng10-public-release' \
                 help='where is CzEng 1.0, untarred' \
     defvar SECTION default='' help='extract only this section' \
     defvar FILTER_THRESHOLD default='0.0' help='extract only lines better than this' \
     defvar FNRE default='*train.gz' help='use these input files' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

[ -e $CZENG_SOURCEDIR/data.plaintext-format ] \
|| die "\$CZENG_SOURCEDIR/data.plaintext-format not found"

# Don't continue if we are not preparing the step yet
[ -z "$INIT_ONLY" ] || exit 0

[ "$SECTION" == "" ] || eman addtag $SECTION .

cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
set -o pipefail
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

eval zcat $CZENG_SOURCEDIR/data.plaintext-format/$FNRE \\
| perl -F'\\t' -lane 'next if \$F[1] < $FILTER_THRESHOLD; \\
                      next if "$SECTION" ne "" && \$F[0] !~ /^$SECTION/; \\
                      print \$F[2], "\\t", \$F[3];' \\
| sed 's/&/&amp;/g;s/|/\\&pipe;/g' \\
| gzip -c > corpus.cs-en.txt.gz \\
|| die "Failed to prepare the corpus"

nl=\$(zcat corpus.cs-en.txt.gz | wc -l)

(echo "corpus.cs-en.txt.gz;1;c-$SECTION;cs_txt;untoken;\$nl"; \\
 echo "corpus.cs-en.txt.gz;2;c-$SECTION;en_txt;untoken;\$nl") \\
| sed 's/- /-/' | tr ';' '\t' > corpman.info \\
|| die "Failed to create corpman.info"

echo Done.
eman succeed \$mydir

echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
