#!/bin/bash
# eman seed for installing joshua

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# no vars
touch eman.vars


cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

echo "Obtaining Joshua"
wget http://cs.jhu.edu/~post/files/joshua-v5.0.tgz || die "Failed to download joshua" 
tar xvzf joshua-v5.0.tgz || die "failed to extract joshua-v5.0.tgz"
cd joshua-v5.0 || die "failed to chdir joshua"
joshua=\$(pwd)
export JOSHUA=\$joshua
ant || die "ant failed"

wget https://github.com/joshua-decoder/moore_and_lewis_data_selection/archive/master.zip
unzip master.zip

cd ..
ln -s joshua-v5.0 joshua

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
