#!/bin/bash
# eman step to index large monolingual corpora

function die() { echo "$@" >&2; exit 1; }
set -o pipefail # safer pipes

# Ensure all the required variables are set (or provide the default)
eman \
   defvar SRCCORP default='' help='input monolingual corpus in target language' \
   defvar SRCAUG default='' help='lang+factors' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

PLAYGROUND=`eman path` # eman playground directory
SRCCORPDIR=`eman path $SRCCORP`
WORKDIR=$(pwd)

$PLAYGROUND/corpman $SRCCORP/$SRCAUG \
  || die "$SRCCORP/$SRCAUG not found"

# Don`t continue if we are not preparing the step yet
[ -z "$INIT_ONLY" ] || exit 0

cat << KONEC > eman.command
#!/bin/bash
echo "============================"
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\` 
echo "============================"
set -o pipefail
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

$PLAYGROUND/corpman $SRCCORP/$SRCAUG --dump | gzip -c > corpus.txt.gz \\
  || die "Failed to find corpus $SRCCORP/$SRCAUG"

mkdir indexes \\
  || die "Failed to mkdir indexes"

cd $PLAYGROUND/LuceneIndexer \\
  || die "Failed to chdir to $PLAYGROUND/LuceneIndexer"

./index inputfile=$WORKDIR/corpus.txt.gz lucene.index.directory=$WORKDIR/indexes \\
|| die "Failed to prepare the index"

echo Done.
eman succeed \$mydir

echo "============================"
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "============================"

KONEC
