#!/bin/bash
# eman step to index large monolingual corpora

function die() { echo "$@" >&2; exit 1; }
set -o pipefail # safer pipes

PLAYGROUND=`eman path` # eman playground directory

# Ensure all the required variables are set (or provide the default)
eman \
   defvar SRCCORP default='' help='input monolingual corpus in target language' \
   defvar SRCAUG default='' help='lang+factors' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

[ -e $SRCCORP ] \
|| die "\$SRCCORP not found"

SRCCORPDIR=`eman path $SRCCORP`

# other vars, not influencing exact output
JOBS=${JOBS:-30}
SPLIT_TO_SIZE=${SPLIT_TO_SIZE:-30000}
WORKDIR=$(pwd)

cmd="mkdir indexes && cd $PLAYGROUND/LuceneIndexer && ./index inputfile=$SRCCORP lucene.index.directory=$WORKDIR/indexes"

# Don`t continue if we are not preparing the step yet
[ -z "$INIT_ONLY" ] || exit 0

cat << KONEC > eman.command
#!/bin/bash
echo "============================"
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\` 
echo "============================"
set -o pipefail
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

$cmd \\
|| die "Failed to prepare the index"

echo Done.
eman succeed \$mydir

echo "============================"
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "============================"

KONEC
