#!/bin/bash
# eman step to score baseline translation

function die() { echo "$@" >&2; exit 1; }
set -o pipefail # safer pipes

PLAYGROUND=`eman path` # eman playground directory
LUCSCOREDIR=`pwd` # actual directory (lucindexscore)
STEPNAME=$(basename $(pwd))


# Ensure all the required variables are set (or provide the default)
eman \
   defvar INDEXDIR default='' help='directory with lucene index' \
   defvar SRCCORP default='' help='corpora according which should be searched' \
   defvar SRCAUG default='' help='lang+factor of SRCCORP' \
   defvar CUT default='3' help='cut-off limit for lucene' \
   defvar OPTIONS default='' help='options for lucene filtering' \
   defvar OUTCORP same.as='STEPNAME' help='filename of the output' \
   defvar OUTLANG default='' help='language of output' \
   defvar OUTFACTORS default='' help='factors of output' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

# Check our input
[ -e $PLAYGROUND/$INDEXDIR/indexes ] \
|| die "\$INDEXDIR not found"

$PLAYGROUND/corpman $SRCCORP/$SRCAUG \
  || die "$SRCCORP/$SRCAUG not found"

# Preregister corpora
$PLAYGROUND/corpman register -- output-txt.txt.gz \
  -1	$OUTCORP-txt	$OUTLANG	$OUTFACTORS	-1	0 \
|| die "Can't register corpus"

$PLAYGROUND/corpman register -- output-lineids.txt.gz \
  -1	$OUTCORP-lineids	$OUTLANG	$OUTFACTORS	-1	0 \
|| die "Can't register corpus"

# Don`t continue if we are not preparing the step yet
[ -z "$INIT_ONLY" ] || exit 0

cat > eman.command << KONEC
#!/bin/bash
echo "============================"
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\` 
echo "============================"

mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

$PLAYGROUND/corpman $SRCCORP/$SRCAUG --dump | gzip -c > corpus.txt.gz \\
  || die "Failed to find corpus $SRCCORP/$SRCAUG"

cd $PLAYGROUND/LuceneIndexer \\
  || die "Failed to chdir to $PLAYGROUND/LuceneIndexer"

./scoreBySentence inputfile=$LUCSCOREDIR/corpus.txt.gz lucene.index.directory=$PLAYGROUND/$INDEXDIR/indexes score.nbest=$CUT $OPTIONS | gzip -c > $LUCSCOREDIR/output.txt.gz \\
  || die "Failed to filter index"

cd $LUCSCOREDIR \\
  || die "Failed to chdir to $LUCSCOREDIR"

zcat output.txt.gz | cut -f 3 | grep -v '^$' | gzip -c > output-txt.txt.gz \\
  || die "Failed to filter text"

zcat output.txt.gz | cut -f 1 | grep -v '^$' | gzip -c > output-lines.txt.gz \\
  || die "Failed to filter linenums"

LINECOUNT=`zcat output-txt.txt.gz | wc -l`

$PLAYGROUND/corpman register -- output-txt.txt.gz \
  -1	$OUTCORP-txt	$OUTLANG	$OUTFACTORS	$LINECOUNT	0 \
|| die "Can't register linecount of the filtered corpus"

$PLAYGROUND/corpman register -- output-lines.txt.gz \
  -1	$OUTCORP-lineid	$OUTLANG	$OUTFACTORS	$LINECOUNT	0 \
|| die "Can't register linecount of the filtered corpus"

echo Done.
eman succeed \$mydir

echo "============================"
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "============================"

KONEC

