#!/bin/bash
# eman step to select filtered lines from the original indexed corpus

function die() { echo "$@" >&2; exit 1; }
set -o pipefail # safer pipes

PLAYGROUND=`eman path` # eman playground directory

# Ensure all the required variables are set (or provide the default)
eman \
   defvar LUCSCORESTEP type=reqstep help='the lucscore step where the lines were selected' \
   defvar OUTCORP help='the name of the output corpus to register' \
   defvar LINES help='how many lines to select' \
   defvar CORPUS inherit='LUCSCORESTEP:OUTCORP' \
   defvar OUTSRCLANG inherit='LUCSCORESTEP:OUTSRCLANG' \
   defvar OUTSRCFACTORS inherit='LUCSCORESTEP:OUTSRCFACTORS' \
   defvar OUTTRGLANG inherit='LUCSCORESTEP:OUTTRGLANG' \
   defvar OUTTRGFACTORS inherit='LUCSCORESTEP:OUTTRGFACTORS' \
   defvar TMPDIR default='/datastore/$USER/tmp' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

# Don`t continue if we are not preparing the step yet
[ -z "$INIT_ONLY" ] || exit 0

cat > eman.command << KONEC
#!/bin/bash
echo "============================"
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\` 
echo "============================"

mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

function mkcorpus() {
  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
  step_file_col=(\$($PLAYGROUND/corpman \$1))
  if [ "\${step_file_col[2]}" == "-1" ]; then
    STEPPATH=\$(eman path \${step_file_col[0]})
    $PLAYGROUND/../scripts/wiseln \$STEPPATH/\${step_file_col[1]} \\
      corpus.\$2.gz \
    || die "Failed to clone \$2 corpus \$1"
  else
    echo "Selecting the column from \$step_file_col"
    eval \$($PLAYGROUND/corpman --cmd \$1) \\
    | gzip -c > corpus.\$2.gz
  fi
}

if [ -n "$OUTSRCLANG" ]
then
  mkcorpus $CORPUS/$OUTSRCLANG+$OUTSRCFACTORS src
  zcat corpus.src.gz \\
  | sed -ne '1,$LINES p' \\
  | gzip -c > output.src.gz \\
  || die "Failed to select the lines"
  $PLAYGROUND/corpman register -- output.src.gz	-1    $OUTCORP        $OUTSRCLANG        $OUTSRCFACTORS     \$(zcat output.src.gz | wc -l)  0 \\
  || die "Can't register linecount of the filtered corpus"
fi

if [ -n "$OUTTRGLANG" ]
then
  mkcorpus $CORPUS/$OUTTRGLANG+$OUTTRGFACTORS trg
  zcat corpus.trg.gz \\
  | sed -ne '1,$LINES p'  \\
  | gzip -c > output.trg.gz \\
  || die "Failed to select the lines"
  $PLAYGROUND/corpman register -- output.trg.gz -1    $OUTCORP        $OUTTRGLANG        $OUTTRGFACTORS     \$(zcat output.trg.gz | wc -l)  0 \\
  || die "Can't register linecount of the filtered corpus"
fi

echo Done.
eman succeed \$mydir

echo "============================"
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "============================"

KONEC

