#!/bin/bash
# eman seed for compiling mgiza

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# no vars
touch eman.vars

cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

wget -O mgizapp.tgz http://sourceforge.net/projects/mgizapp/files/mgizapp-0.7.3-updated.tgz/download
tar xzf mgizapp.tgz || die "mgiza missing"
cd mgizapp || die "Failed to chdir to mgizapp"
cmake CMakeCache.txt || die "Failed to cmake"

make || die "Failed to make"
cd ../ || die "chdir back failed"

ln -s mgizapp/bin bin

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
