#!/bin/bash
# eman seed for constructing an n-gram language model
# binarization now excluded, because there are different (KenLM/IrstLM)
# binarization options

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

PLAYGROUND=`eman path` # eman playground directory

# Ensure all the required variables are set (or provide the default)
eman \
  defvar LMSTEP type=reqstep help='where is the lm' \
  defvar SRILMSTEP type=reqsetp inherit='LMSTEP' help='where is srilm compiled' \
  defvar CORP help='the shortname of corpus' \
  defvar CORPAUG inherit='LMSTEP' help='the language+factors for the lm' \
  defvar TEMPDIR default='/datastore/$USER/tmp' \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

# add source corpus to deps
corpstep=$($PLAYGROUND/corpman --init $CORP/$CORPAUG | cut -f1)
[ ! -z "$corpstep" ] || die "Missing source corpus"

eman add-deps . $corpstep

# Stop here if we are just initing ourselves
[ -z "$INIT_ONLY" ] || exit 0

# Emit the main script to be used in the running phase

tempdir=$TMPDIR
  # best choice for ufal
[ -d $tempdir ] || tempdir=/tmp
  # the default

# convert the dependencies to absolute paths
SRILMDIR=`eman path $SRILMSTEP`

LMDIR=`eman path $LMSTEP`

cat << KONEC > eman.command
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

# init grid environment; sometimes needed for ./augment.pl
. /net/projects/SGE/user/sge_profile

SRILMDIR1="\$(cat $SRILMDIR/srilm.path)/bin/"
SRILMDIR2="\$(cat $SRILMDIR/srilm.path)/bin/i686/"

export PATH=\$SRILMDIR1:\$SRILMDIR2:\$PATH

echo "Using this ngram"
which ngram || die "No ngram"

function mkcorpus() {
  # If local copy of corpus already exists (we are running 'eman continue') remove it first.
  rm -f corpus.\$2.gz
  corpspec=\$($PLAYGROUND/corpman --wait \$1)
  echo "corpman for \$1 returned: \$corpspec" # for the logfile
  step_file_col=(\$corpspec)
  corpfile=\$(eman path \${step_file_col[0]})/\${step_file_col[1]}
  [ -e \$corpfile ] \\
    || die "Failed to prepare \$1, corpus file not found: \$corpfile"
  if [ "\${step_file_col[2]}" == "-1" ]; then
    $PLAYGROUND/../scripts/wiseln \$corpfile \\
      corpus.\$2.gz \
    || die "Failed to clone \$2 corpus \$1"
  else
    echo "Selecting the column \${step_file_col[2]} from \$corpfile"
    zcat \$corpfile | cut -f "\${step_file_col[2]}" \\
    | gzip -c > corpus.\$2.gz
  fi
}

mkcorpus $CORP/$CORPAUG text
lmfilename=\$(cat $LMDIR/lmfilename)

$PLAYGROUND/../scripts/wiseln $LMDIR/\$lmfilename \$lmfilename || die "Failed to clone lm."

ngram -lm \$lmfilename -ppl corpus.text.gz > ppl.txt || die "Failed to calcualte perplexity"

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
