#!/bin/bash

# prune a language model with given threshold

function die() { echo "$@" | tee FAILED >&2; exit 1 ; }

set -o pipefail

if [ -z "$FULLLM" ] \
|| [ -z "$LMPRUNE" ] ; then
  echo "You must set: "
  echo "  \$FULLLM to the step containing the full LM"
  echo "  \$LMPRUNE to N where pruning threshold is 1/(10^N)"
  echo "And optionally: "
  echo "  \$BINARIES to the step containing compiled tools"
  exit 1
fi

echo $FULLLM > eman.deps

if [ -z "$BINARIES" ] ; then
  eval `cat ../$FULLLM/eman.vars | grep '^BINARIES='`
else
  echo $BINARIES >> eman.deps
fi

eval `cat ../$FULLLM/eman.vars | grep '^ORDER=\|^CORP='`

echo $ORDER > var-ORDER
echo $CORP > var-CORP

cat << KONEC > eman.vars
BINARIES=$BINARIES
FULLLM=$FULLLM
PRUNELM=$PRUNELM
KONEC

echo "PRUNELM-$FULLLM:$LMPRUNE" > eman.tag

PRUNESTRING="0."
for i in `seq $(($LMPRUNE - 1))` ; do
  PRUNESTRING="0$PRUNESTRING"
done
PRUNESTRING="${PRUNESTRING}1"

# Stop here if we are just initing ourselves
[ -z "$INIT_ONLY" ] || exit 0

cat << KONEC > eman.command
# This is the command to be run here
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="

# init grid environment
. /net/projects/SGE/user/sge_profile

renice 10 \$\$
function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
set -o pipefail

SRILMDIR1="\`cat ../$BINARIES/srilm.path\`/bin/"
SRILMDIR2="\`cat ../$BINARIES/srilm.path\`/bin/i686/"

export PATH=\$SRILMDIR1:\$SRILMDIR2:\$PATH

echo "Using this ngram:"
which ngram || die "No ngram"

echo "Pruning the language model..."
ngram -lm ../$FULLLM/corpus.lm \\
  -prune $PRUNESTRING \\
  -write-lm ./corpus.lm \\
  || die "Failed to prune LM"

echo DONE > eman.status

echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
