#!/bin/bash

tmpa=/tmp/difexp.$$.tmpa
tmpb=/tmp/difexp.$$.tmpb
echo "-- EXPERIMENT: $1" > $tmpa
echo "++ EXPERIMENT: $2" > $tmpb
if eman traceback "$1" --tag --vars >> $tmpa \
  && eman traceback "$2" --tag --vars >> $tmpb; then
  diff --unified=500 $tmpa $tmpb | less -S
fi
rm -f $tmpa $tmpb
