#!/bin/bash

function die() {
  echo "$@" >&2
  exit 1
}

a=$(eman path --readonly $1)
b=$(eman path --readonly $2)

[ -d "$a" ] || die "Missing $a"
[ -d "$b" ] || die "Missing $b"

a=$(first_existing $a/corpus.translation $a/translated.gz)
b=$(first_existing $b/corpus.translation $b/translated.gz)
[ -f "$a" ] || die "Missing $a"
[ -f "$b" ] || die "Missing $b"

echo Diffing $a and $b

tmp=/tmp/difhyp.$$

#echo `cat $a/BLEU.opt` $a > $tmp.a
#echo `cat $b/BLEU.opt` $b > $tmp.b

autocat $a >> $tmp.a
autocat $b >> $tmp.b

ziplines --delim $tmp.a $tmp.b | less -S

rm $tmp.a $tmp.b
