#!/bin/bash

e1="$1"
e2="$2"

inf=`./output "$e1" in`
if [ -e "$inf.txt" ]; then
  inf="$inf.txt"
fi
echo $inf

tools/compare_translations/merge_src_ref_tst.pl \
  src=$inf \
  ref=`./output "$e1" ref.0` \
  $e1=`./output "$e1"` \
  $e2=`./output "$e2"` \
| tools/compare_translations/sentence_compute.pl \
| tools/compare_translations/sentence_sort.pl \
| tools/compare_translations/to_ansi.pl \
| less --RAW-CONTROL-CHARS
