#!/bin/bash
# 'less' the log of the given SPEC

function die() { echo "$@" >&2; exit 1; }

s=`eman guess "$1"`
[ -d "$s" ] || die "Bad step specifier: $1"

logf=`ls -t $s/log.o* 2>/dev/null | head -n1`
if [ -e "$logf" ]; then
  echo Following $logf
  less $logf
else
  echo "No log yet. Could wait for it but not implemented"
  exit 1
fi
