#!/bin/bash
# simple script to continue a mert experiment that failed

function die() {
  echo "$@" >&2
  exit 1
}
set -o pipefail

[ ! -z "$1" ] || die "usage: $0 exp-identifier"

e=`eman guess $1`

[ -d $e ] || die "Not an experiment: $e";

perl -i~ -pe 's/^(.*(mkcorpus|absolutize_moses|wiseln.*(moses|scorenbest|testbleu)))/# $1/; s/(mert-moses.pl)/$1 --continue/;' $e/eman.command \
|| die "Failed to modify eman.command"

#rm -rf $e/mert-tuning/filtered
# no longer need to remove the filtered...

echo "Now check $e/eman.command and start it over:"
echo "  eman continue $e"


