#!/bin/bash
# simple script to show translation options

function die() {
  echo "$@" >&2
  exit 1
}
set -o pipefail

[ ! -z "$1" ] || die "usage: $0 exp-identifier [dev|test]"

e=`manager.pl --guess $1`
src=$2

[ ! -z "$src" ] || src=test   # default to test

cd $e || die "Can't chdir to $e"

if [ $src == test ]; then
  [ -e filtered-for-eval-opt/moses.ini ] || die "No moses.ini for evaluation data in $e"
  ./moses -f filtered-for-eval-opt/moses.ini -i evaluation.in -verbose 3 2>&1 \
  | less -S
else
  cd mert-tuning || die "Failed to find mert-tuning in $e"
  [ -e run$src.moses.ini ] || die "No run$src.moses.ini"
  ../moses -f run$src.moses.ini -i ../tuning.in -verbose 3 2>&1 | less -S
fi
