#!/bin/bash
# tail -f the log of the given SPEC

function die() { echo "$@" >&2; exit 1; }

s=`if [ -d $1 ]; then echo $1; else eman path --read-only "$1"; fi`
[ -d "$s" ] || die "Bad step specifier: $1"

# under sge, wait for log.o*, otherwise wait for log
if qsub -help nonexistent-file 2>&1 | grep GE >/dev/null 2>/dev/null; then
  # echo SGE
  suffix=.o
else
  # echo no-SGE
  suffix=
fi

logf=`ls -t $s/log$suffix* 2>/dev/null | head -n1`
warned=0
while ! [ -e "$logf" ]; do
  [ $warned == 1 ] || echo "Waiting for logfile of $s"
  warned=1
  sleep 1
  logf=`ls -t $s/log.o* 2>/dev/null | head -n1`
done

if [ -e "$logf" ]; then
  echo Following $logf
  tail -f $logf
fi
