#!/bin/bash
# tail -f the log of the given SPEC

function die() { echo "$@" >&2; exit 1; }

s=`eman guess --readonly "$1"`
[ -d "$s" ] || die "Bad step specifier: $1"

logf=`ls -t $s/log.o* 2>/dev/null | head -n1`
warned=0
while ! [ -e "$logf" ]; do
  [ $warned == 1 ] || echo "Waiting for logfile of $s"
  warned=1
  sleep 1
  logf=`ls -t $s/log.o* 2>/dev/null | head -n1`
done

if [ -e "$logf" ]; then
  echo Following $logf
  tail -f $logf
fi
