#!/bin/bash
set -o pipefail


function show() {
  mert=$1
  if [[ -e exp.eval.$mert/info.mertexp ]]; then
    mert=exp.eval.$mert
  fi
  
  if [[ -e exp.eval.$mert/info.mertexp ]]; then
    echo "==== EVAL: $mert"
    prefix "  " < $mert/VARS
    mert=`cat $mert/info.mertexp`
  fi

  if [[ -e exp.mert.$mert/info.modelexp ]]; then
    mert=exp.mert.$mert
  fi
  
  if [[ -e $mert/info.modelexp ]]; then
    echo "==== MERT: $mert"
    prefix "  " < $mert/VARS
    model=`cat $mert/info.modelexp`
  else
    model=$mert
  fi
  
  if [[ -e $model/VARS ]]; then
    echo "==== MODEL: $model"
    prefix "  " < $model/VARS
  fi
}

for arg in "$@"; do
  show $arg
  for m in `grep "$mert" bleu | cut -f2 | sed 's/<.*//'`; do
    echo By BLEU $arg
    show $m
  done
done
