../augment.pl wmt08/csNm
../augment.pl wmt08/enNm
../augment.pl wmt09/csNm
../augment.pl wmt09/enNm
../augment.pl wmt10/csNm
../augment.pl wmt10/enNm
../augment.pl czeng09-eu/csNm
../augment.pl czeng09-eu/enNm
../augment.pl czeng09-fi/csNm
../augment.pl czeng09-fi/enNm
../augment.pl czeng09-na/csNm
../augment.pl czeng09-na/enNm
../augment.pl czeng09-ne/csNm
../augment.pl czeng09-ne/enNm
../augment.pl czeng09-su/csNm
../augment.pl czeng09-su/enNm
../augment.pl czeng09-te/csNm
../augment.pl czeng09-te/enNm
../augment.pl czeng09-we/csNm
../augment.pl czeng09-we/enNm
../augment.pl emea/csNm
../augment.pl emea/enNm
../augment.pl ps/csNm
../augment.pl ps/enNm
../augment.pl ted/csNm
../augment.pl ted/enNm
../augment.pl monoeuroparl/csNm
../augment.pl mononews07/csNm
../augment.pl mononews08/csNm
../augment.pl mononews09/csNm
../augment.pl mononews10/csNm
../augment.pl mononews11/csNm
../augment.pl monops/csNm
../augment.pl webcoll/csNm
../augment.pl syn200x/csNm
